# coding=utf-8
"""
Django settings for digikunkor project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import datetime


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '67mnnv^vs7&^v87YrV&hd8bw92bu9b%$$#b8728^%93y6==37yb&BBB6*njs*99__==31292319171513117ncdjncdujb'
SITE_NAME = "concough.com"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = []

DEV_ENVIRONMENT = 'local' # can be 'deploy' or 'local' or 'test'
# Application definition

INSTALLED_APPS = (
    'django.contrib.sites',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'main',
    'admin',
    'dataentry',
    'api',
    'graceful_session_cleanup',
    'ckeditor',
    'ckeditor_uploader',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'digikunkor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'filters': 'main.templatetags.filters',
                'afilters': 'admin.templatetags.filters',
            }
        },
    },
]

SITE_ID = 1

WSGI_APPLICATION = 'digikunkor.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'digikunkor.db'),
    }
}

FIXTURE_DIRS = (
    os.path.join(BASE_DIR, 'fixtures'),
)

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Authentication system
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)

ANONYMOUS_USER_ID = None

LOGIN_URL = 'main.auth.login'
LOGIN_REDIRECT_URL = 'main.admin.home'

# Session settings
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 60 * 60    # one hour

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static/production"),
)
STATIC_ROOT = 'static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_DIRS = (
    os.path.join(BASE_DIR, "media"),
)
MEDIA_URL = '/media/'

SMS_PAYAMRESAN_USERNAME = '****'
SMS_PAYAMRESAN_PASSWORD = '****'
SMS_PAYAMRESAN_FROM = "-1"
SMS_PAYAMRESAN_GET_URL = "http://www.payam-resan.com/APISend.aspx"

SMS_KAVENEGAR_API_KEY = '736C4E4B574E7***'

SMS_KAVENEGAR_SIGNUP_SMS_TEMPLATE = 'concoughsmssignup'
SMS_KAVENEGAR_SIGNUP_CALL_TEMPLATE = 'concoughcallsignup'
SMS_KAVENEGAR_PASS_SMS_TEMPLATE = 'concoughsmspass'
SMS_KAVENEGAR_PASS_CALL_TEMPLATE = 'concoughcallpass'
SMS_KAVENEGAR_CHECKOUT_SMS_TEMPLATE = 'concoughsmscheckout'
SMS_KAVENEGAR_BUG_REPORT_SMS_TEMPLATE = 'concoughsmsbugreport'
SMS_KAVENEGAR_EDITOR_PAYMENT_SMS_TEMPLATE = 'concoughsmseditorpayment'

SMS_ALLOWED_IN_DAY = 3
CALL_ALLOWED_IN_DAY = 1

CDN_PREFIX = ""

# Jwt Settings
JWT_AUTH = {
    'JWT_SECRET_KEY': SECRET_KEY,
    'JWT_PUBLIC_KEY': None,
    'JWT_PRIVATE_KEY': None,
    'JWT_ALGORITHM': 'HS256',
    'JWT_LEEWAY': 0,
    'JWT_AUDIENCE': None,
    'JWT_ISSUER': None,
    'JWT_VERIFY': True,
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_ALLOW_REFRESH': True,

    # 'JWT_EXPIRATION_DELTA': datetime.timedelta(seconds=3600 * 24 * 3),
    'JWT_EXPIRATION_DELTA': datetime.timedelta(seconds=3600 * 6),
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=7),

    # 'JWT_EXPIRATION_DELTA': datetime.timedelta(seconds=30),
    # 'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(seconds=60),

    'JWT_AUTH_HEADER_PREFIX': 'JWT',
    'JWT_RESPONSE_PAYLOAD_HANDLER': 'main.app.jwt_response_payload_handler11'
}

REST_FRAMEWORK = {
    # "DEFAULT_PERMISSION_CLASSES": ('rest_framework.permissions.IsAuthenticated', ),
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework.authentication.BasicAuthentication',
        # 'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        # 'oauth2_provider.ext.rest_framework.OAuth2Authentication', )
    ),
    'EXCEPTION_HANDLER': 'api.helpers.exception_helpers.custom_exception_handler'
}

DOWNLOAD_LINKS = {
    "ios": "https://new.sibapp.com/applications/concough",
    "android": "https://play.google.com/store/apps/details?id=com.concough.android.concough",
    "desktop": ""
}

MONGODB_URI = ""
MONGODB_DB = ""

CKEDITOR_UPLOAD_PATH = "ck/"
CKEDITOR_FILENAME_GENERATOR = 'main.utils.get_help_filename'
CKEDITOR_RESTRICT_BY_DATE = False
CKEDITOR_RESTRICT_BY_USER = False
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'width': '100%'
    }
}

USER_WALLET = 500

if DEV_ENVIRONMENT == 'local':
    SITE_ID = 1
    ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

    MONGODB_URI = "mongodb://test3:test@192.168.0.21:27017/mt1"
    MONGODB_DB = "mt1"

    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
#            'LOCATION': 'unix:/home/abolfazl/PycharmProjects/digikunkor/memcached.sock',
            'LOCATION': '127.0.0.1:11211',
            'TIMEOUT': 60 * 60,
            'KEY_PREFIX': 'CONCOUGH',
        }
    }
    CACHALOT_ENABLED = True
    CACHALOT_CACHE = 'default'


    # Application definition
    INSTALLED_APPS += (
        'debug_toolbar',
        'cachalot',
        'rest_framework',
        'rest_framework_jwt',
    )

    MIDDLEWARE_CLASSES += ('debug_toolbar.middleware.DebugToolbarMiddleware', )

    DEBUG_TOOLBAR_PANELS = [
        'debug_toolbar.panels.versions.VersionsPanel',
        'debug_toolbar.panels.timer.TimerPanel',
        'debug_toolbar.panels.settings.SettingsPanel',
        'debug_toolbar.panels.headers.HeadersPanel',
        'debug_toolbar.panels.request.RequestPanel',
        'debug_toolbar.panels.sql.SQLPanel',
        'debug_toolbar.panels.staticfiles.StaticFilesPanel',
        'debug_toolbar.panels.templates.TemplatesPanel',
        'debug_toolbar.panels.cache.CachePanel',
        'debug_toolbar.panels.signals.SignalsPanel',
        'debug_toolbar.panels.logging.LoggingPanel',
        'debug_toolbar.panels.redirects.RedirectsPanel',
        'cachalot.panels.CachalotPanel',
    ]

    # Email Settings
    EMAIL_HOST = 'localhost'
    EMAIL_PORT = 1025
    EMAIL_HOST_USER = '***@gmail.com'
    EMAIL_HOST_PASSWORD = '***'
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    EMAIL_INFO_ADDR = 'کنکوق <info@concough.com>'
    EMAIL_NO_REPLY_ADDR = 'کنکوق <no-reply@concough.com>'

elif DEV_ENVIRONMENT == 'deploy':
    SITE_ID = 2
    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = False
    TEMPLATE_DEBUG = DEBUG

    ALLOWED_HOSTS = ['concough.com', 'www.concough.com', '.concough.com', 'zhycan.com', 'concough.zhycan.com', '.zhycan.com']

    MONGODB_URI = "mongodb://concoughPanelAdmin:****@159.*.*.192:39412/concough"
    # MONGODB_URI = "mongodb://concoughPanelAdmin:****@localhost:19595/concough"
    MONGODB_DB = "concough"

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'concough',
            'USER': 'abo***h',
            'PASSWORD': '****',
            'HOST': '127.0.0.1',
            'PORT': '3306',
            # 'OPTIONS': 'SET storage_engine=INNODB,character_set_connection=utf8,collation_connection=utf8_general_ci',
        }
    }

    # cache settings
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
            'LOCATION': 'unix:/home/abolfazlbeh/webapps/concough/cc/memcached.sock',
            'TIMEOUT': 60 * 60,
            'KEY_PREFIX': 'CONCOUGH',
        }
    }

    CACHALOT_ENABLED = True
    CACHALOT_CACHE = 'default'

    # Application definition
    INSTALLED_APPS += (
        'cachalot',
        'rest_framework',
        'rest_framework_jwt',
    )

    CDN_PREFIX = "https://cdn.zhycan.com/concough/"
    STATIC_ROOT = '/home/abolfazlbeh/webapps/zhycan_cdn'
    MEDIA_ROOT = '/home/abolfazlbeh/webapps/concough_media'

    # STATIC_ROOT = '/home/albehroozi/webapps/digikonkur_statics/'
    # MEDIA_ROOT = '/home/albehroozi/webapps/digikonkur_media/'

    # Authentication system
    LOGIN_URL = 'main.auth.login'
    KEEP_LOGGED_DURATION = 3 * 24 * 60 * 60

    # Email Settings
    EMAIL_HOST = 'smtp.webfaction.com'
    EMAIL_HOST_USER = 'con***'
    EMAIL_HOST_PASSWORD = '****'
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_INFO_ADDR = 'کنکوق <info@concough.com>'
    EMAIL_NO_REPLY_ADDR = 'کنکوق <no-reply@concough.com>'

